import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="h-screen w-screen bg-[#1a1a1a] overflow-none">
          <div className="flex flex-row h-full">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}