import "./globals.css";
import Navigation from "../components/containers/Navigation";
import FullPageWrapper from "../components/containers/FullPageWrapper";
import SizeChecker from "../components/SizeChecker";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="h-screen w-screen py-4 pr-4 bg-[#1a1a1a] overflow-hidden">
          <div className="flex flex-row h-full">
            <Navigation />
              <FullPageWrapper>
                {children}
              </FullPageWrapper>
            <SizeChecker />
          </div>
        </div>
      </body>
    </html>
  );
}
